ERROR 2025-01-22 19:27:32,366 log Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\views.py", line 158, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\mixins.py", line 118, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\mixins.py", line 82, in post
    response = self.form_valid(form)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\views.py", line 164, in form_valid
    self.user, resp = form.try_save(self.request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\forms.py", line 456, in try_save
    return super().try_save(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\forms.py", line 390, in try_save
    user = self.save(request)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\accounts\forms.py", line 61, in save
    user = super().save(request)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\forms.py", line 400, in save
    adapter.save_user(request, user, self)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\allauth\account\adapter.py", line 328, in save_user
    user.save()
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 1013, in save_base
    post_save.send(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\signals.py", line 16, in send_newsletter
    send_mail(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: Invalid user or password! 1737566852-URbMxa0Oh8c0')
ERROR 2025-01-22 19:27:32,498 basehttp "POST /accounts/signup/ HTTP/1.1" 500 251786
ERROR 2025-01-23 16:47:28,757 log Internal Server Error: /board/comments/5/accept/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 206, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 34, in form_valid
    send_mail(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\__init__.py", line 88, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: Invalid user or password! 1737643647-PlZDDkCpHW20')
ERROR 2025-01-23 16:47:28,828 basehttp "POST /board/comments/5/accept/ HTTP/1.1" 500 149350
ERROR 2025-01-23 20:05:10,816 basehttp "POST /board/create/ HTTP/1.1" 500 115292
ERROR 2025-01-23 20:11:14,552 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 118, in form_valid
    from_email='vitalivoloshin1975@yandex.co.il', recipient_list=[response.post.user.email],
                                                                  ^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'post'
ERROR 2025-01-23 20:11:14,616 basehttp "POST /board/create/ HTTP/1.1" 500 115248
ERROR 2025-01-23 20:12:14,733 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 123, in get_success_url
    return reverse_lazy('post-detail', kwargs={'pk': self.object.post.pk})
                                                     ^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'post'
ERROR 2025-01-23 20:12:14,922 basehttp "POST /board/create/ HTTP/1.1" 500 127434
ERROR 2025-01-23 20:12:44,709 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:12:44,792 basehttp "POST /board/create/ HTTP/1.1" 500 150277
ERROR 2025-01-23 20:17:21,742 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:17:21,805 basehttp "POST /board/create/ HTTP/1.1" 500 150262
ERROR 2025-01-23 20:18:46,580 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:18:46,648 basehttp "POST /board/create/ HTTP/1.1" 500 150264
ERROR 2025-01-23 20:20:06,378 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:20:06,444 basehttp "POST /board/create/ HTTP/1.1" 500 150263
ERROR 2025-01-23 20:21:16,943 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
ERROR 2025-01-23 20:21:17,011 basehttp "POST /board/create/ HTTP/1.1" 500 150141
ERROR 2025-01-23 20:22:28,025 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:22:28,092 basehttp "POST /board/create/ HTTP/1.1" 500 150263
ERROR 2025-01-23 20:25:10,323 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 123, in get_success_url
    return reverse('post-detail', kwargs={'pk': self.object.pk})
           ^^^^^^^
NameError: name 'reverse' is not defined. Did you mean: 'reversed'?
ERROR 2025-01-23 20:25:10,388 basehttp "POST /board/create/ HTTP/1.1" 500 127186
ERROR 2025-01-23 20:25:23,182 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 120, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 123, in get_success_url
    return reverse('post-detail', kwargs={'pk': self.object.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
ERROR 2025-01-23 20:25:23,260 basehttp "POST /board/create/ HTTP/1.1" 500 137917
ERROR 2025-01-23 20:38:29,941 log Internal Server Error: /board/comments/1/accept/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 84, in get_form_class
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Specifying both 'fields' and 'form_class' is not permitted.
ERROR 2025-01-23 20:38:29,999 basehttp "GET /board/comments/1/accept/ HTTP/1.1" 500 121691
ERROR 2025-01-24 12:34:01,127 log Internal Server Error: /board/subscriptions/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 43, in subscriptions
    return render(
           ^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\template\base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 7: 'block'. Looking for one of: endblock.
ERROR 2025-01-24 12:34:01,207 basehttp "GET /board/subscriptions/ HTTP/1.1" 500 201798
ERROR 2025-01-24 16:24:19,996 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 159, in form_valid
    response = form.save()
               ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 1013, in save_base
    post_save.send(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\signals.py", line 21, in send_newsletter
    recipient_list=[instance.email],
                    ^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'email'
ERROR 2025-01-24 16:24:20,078 basehttp "POST /board/create/ HTTP/1.1" 500 138375
ERROR 2025-01-24 16:34:36,604 log Internal Server Error: /board/create/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'traders'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\views.py", line 159, in form_valid
    response = form.save()
               ^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\base.py", line 1013, in save_base
    post_save.send(
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\board\signals.py", line 14, in send_newsletter
    emails = User.objects.filter(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'traders'.
ERROR 2025-01-24 16:34:36,786 basehttp "POST /board/create/ HTTP/1.1" 500 197919
ERROR 2025-01-24 16:45:00,070 log Internal Server Error: /admin/board/post/
Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: board_post.category_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vital\Bulletin_Board_MMORPG\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: board_post.category_id
ERROR 2025-01-24 16:45:00,191 basehttp "GET /admin/board/post/ HTTP/1.1" 500 211416
